### ISSUE TITLE
**Phase 3** (Connecting Phase)

### ISSUE THREAD

**Issue by m241dan** [m241dan/CSCI3308GroupProject#15]
The previous phase created basic layers for the application. This will allow each individual layer to be developed on its own.

**Phase Goals**
Begin connecting front-end to the back-end with the integration layer that was create in Phase 2.

Start developing system acceptance tests that allow us to quickly test the next branch each time feature branches are merged to next.

 - **Development / Design**
   - [x] #7 Finish landing page / convert to ejs
   - [x] Adjust front-end to use the integration javascript functions
   - [x] Write UAT scripts **(move to later phase)**
   - [x] #19 Add user authentication
   - [x] #16 Create a controller for Database
   - [x] #25 `Organization now that everything is merged
   - [x] #21 Registration doesn't check for duplicates
   - [x] Either need a script to break up full name into first and last or change form to take first and last
   - [x] #23 Logout does not work
   - [x] #24 Add workout functionality

 - **Testing**
   - [x] Make sure front-end is properly calling back-end scripts and database is populating appropriately from these calls.
