### ISSUE TITLE
**Phase 4** (First Release)

### ISSUE THREAD

**Issue by IronMan61693** [m241dan/CSCI3308GroupProject#20]
With a decent testing platform in place and with all the layers functioning properly, we move onto creating a first release candidate.

 - **Development / Design**
   - [x] #22 Fill in content like workouts and custom workouts
   - [x] Create portion to complete and report on workouts
   - [x] Design Weekly Activity Tracker
   - [x] Design Monthly/Yearly Status Reports
 - **Testing / Discussion**
   - [x] Using the website in its entirely, generate user experiences
