### ISSUE TITLE
**Phase 1** (Design Phase)

### ISSUE THREAD

**Issue by m241dan** [m241dan/CSCI3308GroupProject#8]
This objective of this phase is to produce required documents, as well as establish supporting documentation styles and practices for the following phases. 

 - **Development / Design**
   - [x] Design Document (Milestone 2)
   - [x] User Flow
   - [x] UI Layout Design Rev1
   - [x] Database Design Rev1
   - [ ] #11 Merit/Award System Design
   - [x] #12 Expected Integration Layer Function Call List
 - **Testing / Discussion**
   - [x] Design Document Discussion
   - [x] User Flow Discussion
   - [x] UI Layout Design Discussion
   - [x] Database Design Discussion
   - [x] Merit/Award System Discussion
   - [x] Expected Integration Layer Function Call List
